name: Lint
on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Lint
        run: |
          pip install flake8
          flake8 main.py
